# Generated by Django 4.1.7 on 2023-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstorLogo',
            fields=[
                ('EstorId', models.IntegerField(primary_key=True, serialize=False)),
                ('Logo', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVisual',
            fields=[
                ('ItemId', models.IntegerField(primary_key=True, serialize=False)),
                ('Visual', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
            ],
        ),
    ]
